### ISSUE TITLE
Idea para el desarrollo

### ISSUE THREAD

**Issue by Gastonm123** [SebastianMestre/Clue-Game#2]
Para empezar.. no pretendo cambiar como codeas y tampoco es que sepa demasiado pero te tiro un par de ideas para el programa
- Modularizar el main para que mayormente llame a funciones declaradas en otros .c dedicados a init, movimiento, menues, acusaciones/deducciones, etc.
- Incluir todas las estructuras de datos y datos globales en un .h para poder acceder desde los archivos
- Crear otro .h con los prototipos de todas las funciones declaradas en los modulos par incluirla en los archivos
(con archivos me refiero a los '.c' :P)

**Comment by SebastianMestre** [comment]
Totalmente de acuerdo. Simplemente no habia suficiente codigo como para justificar la separacion antes del ultimo commit.
